# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawnature',
            name='url',
            field=models.CharField(default='', max_length=1000, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawnature',
            name='doc',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
