# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_settingitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingitem',
            old_name='doc_xpath',
            new_name='dov_xpath',
        ),
        migrations.AddField(
            model_name='settingitem',
            name='doc_div_xpath',
            field=models.CharField(default='', max_length=200, verbose_name='正文所在DIV Xpath'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settingitem',
            name='target_url_xpath',
            field=models.CharField(max_length=200, verbose_name='目标莫表页面 Xpath'),
        ),
    ]
