# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190624_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingitem',
            name='allowed_domains',
            field=models.CharField(default='', help_text='主机名不符合该项的URL将会被拦截', max_length=200, verbose_name='URL过滤'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingitem',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
