# Generated by Django 2.2.2 on 2019-06-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190624_0837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lawnature',
            unique_together={('url',)},
        ),
    ]
