# Generated by Django 2.2.2 on 2019-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190625_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingitem',
            name='appendix_xpath',
        ),
        migrations.RemoveField(
            model_name='settingitem',
            name='doc_div_xpath',
        ),
        migrations.RemoveField(
            model_name='settingitem',
            name='dov_xpath',
        ),
        migrations.RemoveField(
            model_name='settingitem',
            name='law_url_xpath',
        ),
        migrations.RemoveField(
            model_name='settingitem',
            name='plan_url_xpath',
        ),
        migrations.RemoveField(
            model_name='settingitem',
            name='policy_url_xpath',
        ),
        migrations.AlterField(
            model_name='settingitem',
            name='target_url_xpath',
            field=models.CharField(max_length=200, verbose_name='目标页面 Xpath'),
        ),
        migrations.AlterField(
            model_name='settingitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='文件夹名称'),
        ),
    ]
