# Generated by Django 2.2.2 on 2019-07-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190701_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawnature',
            name='source',
            field=models.CharField(default='北京市水务局最新法规', max_length=1000, verbose_name='来源'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lawnature',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lawnature',
            name='url',
        ),
    ]
